/* 
 * Apprenda.DeveloperPortal.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ApprendaAPIClient.Models.DeveloperPortal
{
    /// <summary>
    /// ScheduledScalingEvent
    /// </summary>
    public partial class ScheduledScalingEvent :  IEquatable<ScheduledScalingEvent>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets Day
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum DayEnum
        {
            
            /// <summary>
            /// Enum Sunday for "Sunday"
            /// </summary>
            
            Sunday,
            
            /// <summary>
            /// Enum Monday for "Monday"
            /// </summary>
            
            Monday,
            
            /// <summary>
            /// Enum Tuesday for "Tuesday"
            /// </summary>
            
            Tuesday,
            
            /// <summary>
            /// Enum Wednesday for "Wednesday"
            /// </summary>
            
            Wednesday,
            
            /// <summary>
            /// Enum Thursday for "Thursday"
            /// </summary>
            
            Thursday,
            
            /// <summary>
            /// Enum Friday for "Friday"
            /// </summary>
            
            Friday,
            
            /// <summary>
            /// Enum Saturday for "Saturday"
            /// </summary>
            
            Saturday
        }

        /// <summary>
        /// Gets or Sets Day
        /// </summary>
        public DayEnum? Day { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduledScalingEvent" /> class.
        /// </summary>
        /// <param name="Day">Day.</param>
        /// <param name="Time">Time.</param>
        /// <param name="InstanceCount">InstanceCount.</param>
        public ScheduledScalingEvent(DayEnum? Day = default(DayEnum?), DateTime? Time = default(DateTime?), int? InstanceCount = default(int?))
        {
            this.Day = Day;
            this.Time = Time;
            this.InstanceCount = InstanceCount;
        }
        
        /// <summary>
        /// Gets or Sets Time
        /// </summary>
        public DateTime? Time { get; set; }
        /// <summary>
        /// Gets or Sets InstanceCount
        /// </summary>
        public int? InstanceCount { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ScheduledScalingEvent {\n");
            sb.Append("  Day: ").Append(Day).Append("\n");
            sb.Append("  Time: ").Append(Time).Append("\n");
            sb.Append("  InstanceCount: ").Append(InstanceCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ScheduledScalingEvent);
        }

        /// <summary>
        /// Returns true if ScheduledScalingEvent instances are equal
        /// </summary>
        /// <param name="other">Instance of ScheduledScalingEvent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScheduledScalingEvent other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Day == other.Day ||
                    this.Day != null &&
                    this.Day.Equals(other.Day)
                ) && 
                (
                    this.Time == other.Time ||
                    this.Time != null &&
                    this.Time.Equals(other.Time)
                ) && 
                (
                    this.InstanceCount == other.InstanceCount ||
                    this.InstanceCount != null &&
                    this.InstanceCount.Equals(other.InstanceCount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Day != null)
                    hash = hash * 59 + this.Day.GetHashCode();
                if (this.Time != null)
                    hash = hash * 59 + this.Time.GetHashCode();
                if (this.InstanceCount != null)
                    hash = hash * 59 + this.InstanceCount.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
