using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("ApprendaAPIClient")]
[assembly: AssemblyDescription("Visit the Apprenda website at http://www.apprenda.com")]
[assembly: AssemblyConfiguration("This assembly was generated by gsterling at 6/8/2017 11:33:01 AM")]
[assembly: AssemblyCompany("Apprenda, Inc.")]
[assembly: AssemblyProduct("Apprenda Platform")]
[assembly: AssemblyCopyright("Copyright © Apprenda, Inc. 2017")]
[assembly: AssemblyTrademark("Various trademarks held by their respective owners")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("9d3b3176-5845-4f9a-9ed4-b183a3c15679")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("6.9.0.0")]
[assembly: AssemblyFileVersion("6.9.0.0")]
[assembly: AssemblyInformationalVersion("6.9.0.0")]